/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    title: string;
    owner: Principal;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    updatedAt: bigint;
    projectId?: bigint;
    priority: string;
}
export interface PaginationResult {
    currentPage: bigint;
    items: Array<Task>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}
export interface TaskFilter {
    status?: Variant_active_completed;
    sortBy?: SortBy;
    view?: Variant_all_today_upcoming;
    projectId?: bigint;
    priority?: string;
    searchQuery?: string;
}
export interface TaskExport {
    id: bigint;
    title: string;
    projectName?: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    priority: string;
}
export interface Project {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: bigint;
}
export enum SortBy {
    dueDateDesc = "dueDateDesc",
    alphaAsc = "alphaAsc",
    priorityDesc = "priorityDesc",
    createdDesc = "createdDesc",
    createdAsc = "createdAsc",
    alphaDesc = "alphaDesc",
    priorityAsc = "priorityAsc",
    dueDateAsc = "dueDateAsc"
}
export enum Variant_active_completed {
    active = "active",
    completed = "completed"
}
export enum Variant_all_today_upcoming {
    all = "all",
    today = "today",
    upcoming = "upcoming"
}
export interface backendInterface {
    createProject(name: string): Promise<Project>;
    createTask(title: string, description: string | null, dueDate: bigint | null, priority: string, projectId: bigint | null): Promise<Task>;
    deleteProject(id: bigint): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    getAllProjects(): Promise<Array<Project>>;
    getDisplayName(): Promise<string | null>;
    getTasks(filter: TaskFilter, page: bigint | null, limit: bigint | null): Promise<PaginationResult>;
    getTasksForExport(filter: TaskFilter): Promise<Array<TaskExport>>;
    renameProject(id: bigint, name: string): Promise<Project>;
    setDisplayName(displayName: string): Promise<void>;
    toggleTaskComplete(id: bigint): Promise<Task>;
    updateTask(id: bigint, title: string, description: string | null, dueDate: bigint | null, priority: string, projectId: bigint | null): Promise<Task>;
}
import type { PaginationResult as _PaginationResult, SortBy as _SortBy, Task as _Task, TaskExport as _TaskExport, TaskFilter as _TaskFilter } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createProject(arg0: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string | null, arg2: bigint | null, arg3: string, arg4: bigint | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getDisplayName(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayName();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayName();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: TaskFilter, arg1: bigint | null, arg2: bigint | null): Promise<PaginationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(to_candid_TaskFilter_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PaginationResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(to_candid_TaskFilter_n9(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PaginationResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForExport(arg0: TaskFilter): Promise<Array<TaskExport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForExport(to_candid_TaskFilter_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForExport(to_candid_TaskFilter_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameProject(arg0: bigint, arg1: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.renameProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameProject(arg0, arg1);
            return result;
        }
    }
    async setDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDisplayName(arg0);
            return result;
        }
    }
    async toggleTaskComplete(arg0: bigint): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskComplete(arg0);
                return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskComplete(arg0);
            return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string | null, arg3: bigint | null, arg4: string, arg5: bigint | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Task_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PaginationResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginationResult): PaginationResult {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TaskExport_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskExport): TaskExport {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPage: bigint;
    items: Array<_Task>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
}): {
    currentPage: bigint;
    items: Array<Task>;
    totalPages: bigint;
    totalItems: bigint;
    hasNextPage: boolean;
    hasPrevPage: boolean;
} {
    return {
        currentPage: value.currentPage,
        items: from_candid_vec_n17(_uploadFile, _downloadFile, value.items),
        totalPages: value.totalPages,
        totalItems: value.totalItems,
        hasNextPage: value.hasNextPage,
        hasPrevPage: value.hasPrevPage
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    projectName: [] | [string];
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: [] | [string];
    priority: string;
}): {
    id: bigint;
    title: string;
    projectName?: string;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    priority: string;
} {
    return {
        id: value.id,
        title: value.title,
        projectName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.projectName)),
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.dueDate)),
        description: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.description)),
        priority: value.priority
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    owner: Principal;
    createdAt: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    description: [] | [string];
    updatedAt: bigint;
    projectId: [] | [bigint];
    priority: string;
}): {
    id: bigint;
    title: string;
    owner: Principal;
    createdAt: bigint;
    completed: boolean;
    dueDate?: bigint;
    description?: string;
    updatedAt: bigint;
    projectId?: bigint;
    priority: string;
} {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.dueDate)),
        description: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.description)),
        updatedAt: value.updatedAt,
        projectId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.projectId)),
        priority: value.priority
    };
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskExport>): Array<TaskExport> {
    return value.map((x)=>from_candid_TaskExport_n19(_uploadFile, _downloadFile, x));
}
function to_candid_SortBy_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TaskFilter_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskFilter): _TaskFilter {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Variant_active_completed;
    sortBy?: SortBy;
    view?: Variant_all_today_upcoming;
    projectId?: bigint;
    priority?: string;
    searchQuery?: string;
}): {
    status: [] | [{
            active: null;
        } | {
            completed: null;
        }];
    sortBy: [] | [_SortBy];
    view: [] | [{
            all: null;
        } | {
            today: null;
        } | {
            upcoming: null;
        }];
    projectId: [] | [bigint];
    priority: [] | [string];
    searchQuery: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_variant_n11(_uploadFile, _downloadFile, value.status)) : candid_none(),
        sortBy: value.sortBy ? candid_some(to_candid_SortBy_n12(_uploadFile, _downloadFile, value.sortBy)) : candid_none(),
        view: value.view ? candid_some(to_candid_variant_n14(_uploadFile, _downloadFile, value.view)) : candid_none(),
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        priority: value.priority ? candid_some(value.priority) : candid_none(),
        searchQuery: value.searchQuery ? candid_some(value.searchQuery) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_completed): {
    active: null;
} | {
    completed: null;
} {
    return value == Variant_active_completed.active ? {
        active: null
    } : value == Variant_active_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    dueDateDesc: null;
} | {
    alphaAsc: null;
} | {
    priorityDesc: null;
} | {
    createdDesc: null;
} | {
    createdAsc: null;
} | {
    alphaDesc: null;
} | {
    priorityAsc: null;
} | {
    dueDateAsc: null;
} {
    return value == SortBy.dueDateDesc ? {
        dueDateDesc: null
    } : value == SortBy.alphaAsc ? {
        alphaAsc: null
    } : value == SortBy.priorityDesc ? {
        priorityDesc: null
    } : value == SortBy.createdDesc ? {
        createdDesc: null
    } : value == SortBy.createdAsc ? {
        createdAsc: null
    } : value == SortBy.alphaDesc ? {
        alphaDesc: null
    } : value == SortBy.priorityAsc ? {
        priorityAsc: null
    } : value == SortBy.dueDateAsc ? {
        dueDateAsc: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_all_today_upcoming): {
    all: null;
} | {
    today: null;
} | {
    upcoming: null;
} {
    return value == Variant_all_today_upcoming.all ? {
        all: null
    } : value == Variant_all_today_upcoming.today ? {
        today: null
    } : value == Variant_all_today_upcoming.upcoming ? {
        upcoming: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
