/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'projectId' : IDL.Opt(IDL.Nat),
  'priority' : IDL.Text,
});
export const SortBy = IDL.Variant({
  'dueDateDesc' : IDL.Null,
  'alphaAsc' : IDL.Null,
  'priorityDesc' : IDL.Null,
  'createdDesc' : IDL.Null,
  'createdAsc' : IDL.Null,
  'alphaDesc' : IDL.Null,
  'priorityAsc' : IDL.Null,
  'dueDateAsc' : IDL.Null,
});
export const TaskFilter = IDL.Record({
  'status' : IDL.Opt(
    IDL.Variant({ 'active' : IDL.Null, 'completed' : IDL.Null })
  ),
  'sortBy' : IDL.Opt(SortBy),
  'view' : IDL.Opt(
    IDL.Variant({ 'all' : IDL.Null, 'today' : IDL.Null, 'upcoming' : IDL.Null })
  ),
  'projectId' : IDL.Opt(IDL.Nat),
  'priority' : IDL.Opt(IDL.Text),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const PaginationResult = IDL.Record({
  'currentPage' : IDL.Nat,
  'items' : IDL.Vec(Task),
  'totalPages' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'hasNextPage' : IDL.Bool,
  'hasPrevPage' : IDL.Bool,
});
export const TaskExport = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'projectName' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Opt(IDL.Text),
  'priority' : IDL.Text,
});

export const idlService = IDL.Service({
  'createProject' : IDL.Func([IDL.Text], [Project], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [Task],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getTasks' : IDL.Func(
      [TaskFilter, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [PaginationResult],
      ['query'],
    ),
  'getTasksForExport' : IDL.Func(
      [TaskFilter],
      [IDL.Vec(TaskExport)],
      ['query'],
    ),
  'renameProject' : IDL.Func([IDL.Nat, IDL.Text], [Project], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'toggleTaskComplete' : IDL.Func([IDL.Nat], [Task], []),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [Task],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'projectId' : IDL.Opt(IDL.Nat),
    'priority' : IDL.Text,
  });
  const SortBy = IDL.Variant({
    'dueDateDesc' : IDL.Null,
    'alphaAsc' : IDL.Null,
    'priorityDesc' : IDL.Null,
    'createdDesc' : IDL.Null,
    'createdAsc' : IDL.Null,
    'alphaDesc' : IDL.Null,
    'priorityAsc' : IDL.Null,
    'dueDateAsc' : IDL.Null,
  });
  const TaskFilter = IDL.Record({
    'status' : IDL.Opt(
      IDL.Variant({ 'active' : IDL.Null, 'completed' : IDL.Null })
    ),
    'sortBy' : IDL.Opt(SortBy),
    'view' : IDL.Opt(
      IDL.Variant({
        'all' : IDL.Null,
        'today' : IDL.Null,
        'upcoming' : IDL.Null,
      })
    ),
    'projectId' : IDL.Opt(IDL.Nat),
    'priority' : IDL.Opt(IDL.Text),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const PaginationResult = IDL.Record({
    'currentPage' : IDL.Nat,
    'items' : IDL.Vec(Task),
    'totalPages' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'hasNextPage' : IDL.Bool,
    'hasPrevPage' : IDL.Bool,
  });
  const TaskExport = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'projectName' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Opt(IDL.Text),
    'priority' : IDL.Text,
  });
  
  return IDL.Service({
    'createProject' : IDL.Func([IDL.Text], [Project], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [Task],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getTasks' : IDL.Func(
        [TaskFilter, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [PaginationResult],
        ['query'],
      ),
    'getTasksForExport' : IDL.Func(
        [TaskFilter],
        [IDL.Vec(TaskExport)],
        ['query'],
      ),
    'renameProject' : IDL.Func([IDL.Nat, IDL.Text], [Project], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'toggleTaskComplete' : IDL.Func([IDL.Nat], [Task], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };