/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaginationResult {
  'currentPage' : bigint,
  'items' : Array<Task>,
  'totalPages' : bigint,
  'totalItems' : bigint,
  'hasNextPage' : boolean,
  'hasPrevPage' : boolean,
}
export interface Project {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
}
export type SortBy = { 'dueDateDesc' : null } |
  { 'alphaAsc' : null } |
  { 'priorityDesc' : null } |
  { 'createdDesc' : null } |
  { 'createdAsc' : null } |
  { 'alphaDesc' : null } |
  { 'priorityAsc' : null } |
  { 'dueDateAsc' : null };
export interface Task {
  'id' : bigint,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : [] | [string],
  'updatedAt' : bigint,
  'projectId' : [] | [bigint],
  'priority' : string,
}
export interface TaskExport {
  'id' : bigint,
  'title' : string,
  'projectName' : [] | [string],
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'description' : [] | [string],
  'priority' : string,
}
export interface TaskFilter {
  'status' : [] | [{ 'active' : null } | { 'completed' : null }],
  'sortBy' : [] | [SortBy],
  'view' : [] | [{ 'all' : null } | { 'today' : null } | { 'upcoming' : null }],
  'projectId' : [] | [bigint],
  'priority' : [] | [string],
  'searchQuery' : [] | [string],
}
export interface _SERVICE {
  'createProject' : ActorMethod<[string], Project>,
  'createTask' : ActorMethod<
    [string, [] | [string], [] | [bigint], string, [] | [bigint]],
    Task
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getDisplayName' : ActorMethod<[], [] | [string]>,
  'getTasks' : ActorMethod<
    [TaskFilter, [] | [bigint], [] | [bigint]],
    PaginationResult
  >,
  'getTasksForExport' : ActorMethod<[TaskFilter], Array<TaskExport>>,
  'renameProject' : ActorMethod<[bigint, string], Project>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'toggleTaskComplete' : ActorMethod<[bigint], Task>,
  'updateTask' : ActorMethod<
    [bigint, string, [] | [string], [] | [bigint], string, [] | [bigint]],
    Task
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];